discover:
  require-data-encryption: true
server:
  port: 8069
spring:
  application:
    name: event-discovery
  config:
    import:
      - classpath:/exclude.yml
      - classpath:/datasource.yml
      - classpath:/kafka.yml
      - classpath:/logging.yml
      - classpath:/debezium.yml

