spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    url: ${POSTGRES_JDBC}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        c3p0:
          timeout: 30000